---
create_listener: "{%- if oracle_install_option_gi is defined -%}
                     False
                  {%- elif oracle_install_option_gi is undefined -%}
                        {%- if dbh is defined and dbh.listener_name is defined -%}
                            True
                        {%- else -%}
                            False
                        {%- endif -%}
                    {%- endif -%}"

listener_name: LISTENER
listener_protocols: TCP
listener_port: 1521

listener_home: "{%- if lsnrinst is defined -%}
                  {%- if db_homes_config[lsnrinst.home]['oracle_home'] is defined -%}{{db_homes_config[lsnrinst.home]['oracle_home']}}
                  {%- else -%}{{oracle_base}}/{{db_homes_config[lsnrinst.home]['version']}}/{{db_homes_config[lsnrinst.home]['home']}}
                  {%- endif -%}
                {%- elif tnsinst is defined -%}
                  {%- if db_homes_config[tnsinst.home]['oracle_home'] is defined -%}{{db_homes_config[tnsinst.home]['oracle_home']}}
                  {%- else -%}{{oracle_base}}/{{db_homes_config[tnsinst.home]['version']}}/{{db_homes_config[tnsinst.home]['home']}}
                  {%- endif -%}
                {%- elif sqlnetinst is defined -%}
                  {%- if db_homes_config[sqlnetinst.home]['oracle_home'] is defined -%}{{db_homes_config[sqlnetinst.home]['oracle_home']}}
                  {%- else -%}{{oracle_base}}/{{db_homes_config[sqlnetinst.home]['version']}}/{{db_homes_config[sqlnetinst.home]['home']}}
                  {%- endif -%}
                {%- endif -%}"

oracle_env_lsnrctl:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_HOME: "{{ listener_home }}"
  LD_LIBRARY_PATH: "{{ listener_home }}/lib"
  PATH: "{{ listener_home}}/bin:$PATH:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin"
