---
namespace: opitzconsulting
name: ansible_oracle
description: This is the collection of ansible-oracle from Branch oc on https://github.com/opitzconsulting/ansible-oracle
version: 3.0.0
readme: README.md
authors:
  - Mikael Sandström
  - OPITZ CONSULTING
  - Thorsten Bruhns
tags:
  - oracle
