---
galaxy_info:
  role_name: oradb_manage_oraclenet
  author: Thorsten Bruhns
  description: Manage SQLNet files in ORACLE_HOME
  company: Thorsten Bruhns

  license: license (MIT)

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw-meta
