---
# tasks file for manage-db

# Configure listener.ora, sqlnet.ora and tnsnames.ora
- include_role:
    name: oradb-manage-oraclenet
  tags:
    - listener
    - listener2

- include_tasks: listener.yml
  with_items:
    - "{{ oracle_databases }}"
  loop_control:
    loop_var: dbh
  when: create_listener and oracle_databases is defined and listener_installed is not defined
  tags: listener

- name: manage-db | Add change-pdb script
  template:
    src: pdb.sql.j2
    dest: "{{ oracle_user_home }}/.Scripts/chpdb.sql"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0644
  tags: sql_script

- include_tasks: manage-db.yml
  with_items:
    - "{{ oracle_databases }}"
  loop_control:
    loop_var: dbh
  when: oracle_databases is defined
  tags: create_db,dbca,customdbcatemplate,dotprofile_db

- name: manage-db | Check if database is running
  shell: ps -ef |grep pmon |grep -v grep
  tags:
    - psout
  register: psout
  changed_when: false
  failed_when: false
  ignore_errors: true

- debug: var=psout.stdout_lines  # noqa unnamed-task
  changed_when: false
  failed_when: false
  when: psout is defined
  tags:
    - psout
