---
galaxy_info:
  role_name: oraswdb_manage_patches
  author: Mikael Sandström
  description: Install/Remove Patches from Oracle Database Homes
  company: Mikael Sandström

  license: license (MIT)

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw-meta
