---
- name: Disable Transparent Hugepages (runtime)
  ansible.builtin.shell: if test -f /sys/kernel/mm/transparent_hugepage/enabled; then echo never > /sys/kernel/mm/transparent_hugepage/enabled; fi;
  # noqa no-changed-when
  tags: tphnuma
