---
apply_patches_db: false
db_homes_config:
  18300-base:
    home: db1-base
    version: 18.3.0.0
    edition: EE
  12201-latest:
    home: db1-latest
    version: 12.2.0.1
    edition: EE
    opatch_minversion: 12.2.0.1.12
    opatchauto:
      - patchid: 28183653
        patchversion: 12.2.0.1.180717
        state: present
        subpatches:
          - 28163133
          - 28163190

  11204-latest:
    home: db1-latest
    version: 11.2.0.4
    edition: EE
    opatch_minversion: 11.2.0.3.6
    opatchauto:
      - patchid: 27967757
        patchversion: 11.2.0.4.180717
        state: present
        subpatches:
          - 27734982

db_homes_installed:
  - home: 18300-base
    apply_patches: false
    state: present
