---
galaxy_info:
  author: Thorsten Bruhns
  description: Oracle RMAN Backup for ansible-oracle
  company: Thorsten Bruhns

  license: license (MIT)

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw-meta
