---
name: Ansible Lint

on:
  pull_request:
    branches:
      - oc
      - master
  push:
    branches:
      - 'pr*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Lint roles
        # Use custom action repo due to open PRs 43 and 48
        uses: Rendanic/ansible-lint-action@tbr
        with:
          targets: |
            roles/common
            roles/cxoracle
            roles/oraasm-createdg
            roles/oraasm-manage-diskgroups
            roles/oradb-datapatch
            roles/oradb-manage-db
            roles/oradb-manage-grants
            roles/oradb-manage-oraclenet
            roles/oradb-manage-parameters
            roles/oradb-manage-pdb
            roles/oradb-manage-profiles
            roles/oradb-manage-redo
            roles/oradb-manage-roles
            roles/oradb-manage-services
            roles/oradb-manage-statspack
            roles/oradb-manage-tablespace
            roles/oradb-manage-users
            roles/oradb-rman
            roles/orahost
            roles/orahost-cron
            roles/orahost-logrotate
            roles/orahost-ssh
            roles/orahost-storage
            roles/orasw-meta
            roles/oraswdb-golden-image
            roles/oraswgi-golden-image
            roles/oraswdb-install
            roles/oraswdb-manage-patches
            roles/oraswgi-install
            roles/oraswgi-manage-patches
            roles/oraswgi-opatch
            # deprecated roles
            roles/oradb-create
            roles/oradb-delete
            
          args: ""
